### ISSUE TITLE
doesn't build on ghc 8.0 branch tip 

### ISSUE THREAD

**Issue by cartazio** [haskell/directory#48]
theres a missing import of fromMaybe from Data.Maybe,
and even if i fix that theres some other errors such as the following 
```
libraries/directory/System/Directory.hs:1548:10: error:
    • Couldn't match type ‘UTCTime’
                     with ‘time-1.6:Data.Time.Clock.UTC.NominalDiffTime’
      Expected type: Data.Time.Clock.POSIX.POSIXTime
        Actual type: UTCTime
    • In the second argument of ‘setFileTimes’, namely
        ‘(fromMaybe atimeOld atime')’
      In a stmt of a 'do' block:
        setFileTimes
          path' (fromMaybe atimeOld atime') (fromMaybe mtimeOld mtime')
      In the expression:
        do { (atimeOld, mtimeOld) <- fileTimesFromStatus
                                     <$> Posix.getFileStatus path';
             setFileTimes
               path' (fromMaybe atimeOld atime') (fromMaybe mtimeOld mtime') }

libraries/directory/System/Directory.hs:1548:29: error:
    • Couldn't match type ‘time-1.6:Data.Time.Clock.UTC.NominalDiffTime’
                     with ‘UTCTime’
      Expected type: Maybe UTCTime
        Actual type: Maybe Data.Time.Clock.POSIX.POSIXTime
    • In the second argument of ‘fromMaybe’, namely ‘atime'’
      In the second argument of ‘setFileTimes’, namely
        ‘(fromMaybe atimeOld atime')’
      In a stmt of a 'do' block:
        setFileTimes
          path' (fromMaybe atimeOld atime') (fromMaybe mtimeOld mtime')

libraries/directory/System/Directory.hs:1549:10: error:
    • Couldn't match type ‘UTCTime’
                     with ‘time-1.6:Data.Time.Clock.UTC.NominalDiffTime’
      Expected type: Data.Time.Clock.POSIX.POSIXTime
        Actual type: UTCTime
    • In the third argument of ‘setFileTimes’, namely
        ‘(fromMaybe mtimeOld mtime')’
      In a stmt of a 'do' block:
        setFileTimes
          path' (fromMaybe atimeOld atime') (fromMaybe mtimeOld mtime')
      In the expression:
        do { (atimeOld, mtimeOld) <- fileTimesFromStatus
                                     <$> Posix.getFileStatus path';
             setFileTimes
               path' (fromMaybe atimeOld atime') (fromMaybe mtimeOld mtime') }

libraries/directory/System/Directory.hs:1549:29: error:
    • Couldn't match type ‘time-1.6:Data.Time.Clock.UTC.NominalDiffTime’
                     with ‘UTCTime’
      Expected type: Maybe UTCTime
        Actual type: Maybe Data.Time.Clock.POSIX.POSIXTime
    • In the second argument of ‘fromMaybe’, namely ‘mtime'’
      In the third argument of ‘setFileTimes’, namely
        ‘(fromMaybe mtimeOld mtime')’
      In a stmt of a 'do' block:
        setFileTimes
          path' (fromMaybe atimeOld atime') (fromMaybe mtimeOld mtime')
```

**Comment by cartazio** [comment]
cc @bgamari

**Comment by hvr** [comment]
@cartazio that's really weird... wasn't this what #47 was supposed to fix?

**Comment by Rufflewind** [comment]
setFileTimes
                   path' (fromMaybe atimeOld atime') (fromMaybe mtimeOld mtime') }

This is the older version (1.2.6.0).  1.2.6.1 should fix this issue.

Sorry for the mess.

**Comment by cartazio** [comment]
now works for me :) 
pardon the noise :)
